apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "airflow.fullname" . }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "airflow.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "airflow.serviceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "airflow.fullname" . }}-worker
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "airflow.fullname" . }}-worker
subjects:
- kind: ServiceAccount
  name: {{ include "airflow.serviceAccountName" . }}-worker
