apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "airflow.serviceAccountName" . }}
{{- if .Values.oidcEnabled }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.iamRole }}
{{- end }}
  labels:
{{ include "airflow.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "airflow.serviceAccountName" . }}-worker
{{- if .Values.oidcEnabled }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.iamRole }}
{{- end }}
  labels:
{{ include "airflow.labels" . | nindent 4 }}
