{{ if .Values.local.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow.fullname" . }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "airflow.selectorLabels" . | nindent 4 }}
  ports:
    - name: web
      protocol: TCP
      port: 8080
      nodePort: {{ .Values.local.nodeport}}
{{ else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow.fullname" . }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "airflow.selectorLabels" . | nindent 4 }}
{{ end }}