apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: airflowinstances.operator.example.com
spec:
  group: operator.example.com
  names:
    kind: AirflowInstance
    listKind: AirflowInstanceList
    plural: airflowinstances
    singular: airflowinstance
  scope: Namespaced
  # subresources:
  #   status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
