kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: airflow-instance-operator
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: airflow-instance-operator
roleRef:
  kind: ClusterRole
  name: airflow-instance-operator
  apiGroup: rbac.authorization.k8s.io
